### ISSUE TITLE
new Minimal OutputType

### ISSUE THREAD

**Issue by jnyrup** [VerifyTests/Verify.DiffPlex#184]
#### Is the feature request related to a problem

No.

#### Describe the solution

#71 added a new `OutputType.Compact` which greatly reduces the size of the output compared to the default `Full`.
When I use `git diff` I often pass `-U0` to _only_ see the changed lines.
To get a similar output for our [API approval tests](https://github.com/fluentassertions/fluentassertions/blob/develop/Tests/Approval.Tests/ApiApproval.cs) in Fluent Assertions I wrote a custom string comparer to simply skip all unchanged lines.

This is a proposal to add a new `OutputType`, I suggest `Minimal`, which is identical to `Full` except that it excludes unchanged lines.

#### Describe alternatives considered

Write my own custom string comparer

**Comment by SimonCropp** [comment]
LGTM. happy to consider a pull request

**Comment by jnyrup** [comment]
Great to hear.
I'll prepare a PR.
